[Metadata]
Name=everforest-dark-medium
Description=Everforest Dark Medium theme for fcitx5
Version=1.0
Author=RickyJian
ScaleWithDPI=True

[InputPanel]
Font=Sans 12
NormalColor=#d3c6aa                  # 主文字 (fg)
HighlightCandidateColor=#2d353b      # 選中候選字的字色 (bg0)
HighlightColor=#d3c6aa               # 高亮區塊字色（反白區建議用主前景色）
HighlightBackgroundColor=#a7c080     # 選中候選字背景色 (green)
BackgroundColor=#2d353b              # bg0，深底色
Spacing=3

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#2d353b                        # bg0
BorderColor=#d3c6aa                  # status_line2
BorderWidth=2

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#a7c080                        # green

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/PrevPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[InputPanel/NextPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[Menu]
NormalColor=#d3c6aa                  # fg

[Menu/Background]
Color=#232a2e                        # bg_dim/次深色

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color=#a7c080                        # green

[Menu/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu/Separator]
Color=#859289                        # grey1 分隔線（灰）

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
