[Metadata]
Name=everforest-light-soft
Description=Everforest Light Soft theme for fcitx5
Version=1.0
Author=RickyJian
ScaleWithDPI=True

[InputPanel]
Font=Sans 12
NormalColor=#5c6a72                  # 主文字 (fg)
HighlightCandidateColor=#f8f5e4      # 選中候選字的字色 (bg0)
HighlightColor=#5c6a72               # 高亮區塊字色（反白區建議用主前景色）
HighlightBackgroundColor=#8da101     # 選中候選字背景色 (green)
BackgroundColor=#f8f5e4              # bg0，最柔和的淺底色
Spacing=3

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#f8f5e4                        # bg0
BorderColor=#708080                  # status_line2
BorderWidth=2

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#8da101                        # green

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/PrevPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[InputPanel/NextPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[Menu]
NormalColor=#5c6a72                  # fg

[Menu/Background]
Color=#f0ead8                        # bg_dim

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color=#8da101                        # green

[Menu/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu/Separator]
Color=#939f91                        # grey1 分隔線（灰）

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
