[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

[[mgr.prepend_keymap]]
on   = [ "g", "a" ]
run  = "cd /mnt/NVME1/"
desc = "Go to second drive"

[[mgr.prepend_keymap]]
on   = [ "g", "l" ]
run  = "cd ~/.local/"
desc = "Go to .local"
