unbind r
bind r source-file ~/.tmux.conf
set -g mouse on
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
set -g base-index 1
set -g pane-base-index 1
set -g renumber-window on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'donwlewis/everforest-tmux'

set -g @continuum-restore 'off'
set -g @resurrect-dir '~/.tmux/resurrect/'
# Options to make tmux more pleasant
set -g mouse on

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-interval 1


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
